### ISSUE TITLE
Error while attempting to update texlive.infa

### ISSUE THREAD

**Issue by devincaughey** [amaxwell/tlutility#148] opened 2023-11-18 21:04 UTC
I just attempted to use TexLive to update packages on my MacPro (MacOS 12.7.1). I was informed that "the TeX Live installer packages listed here [texlive.infa] must be updated first". When I tried to do this, I received an error that "the update failed". The log output is pasted at end of this email.  I encountered the same error when attempting to update on my MacBook Pro (MacOS 14.1.1).

Any thoughts on how to fix this?
Devin

```
2023-11-18 20:57:41 +0000 Notice +[TLMEnvironment initialize][43733]	Welcome to TeX Live Utility 1.54, running under Mac OS X Version 12.7.1 (Build 21G920) with 12/12 processors active and 32.0 GB physical memory.
2023-11-18 20:57:41 +0000 Notice +[TLMEnvironment _checkProcessUmask][43733]	Process umask = 022
2023-11-18 20:57:41 +0000 Notice +[TLMEnvironment updateEnvironment][43733]	Setting up a new environment for /usr/local/texlive/2023…
2023-11-18 20:57:41 +0000 Notice +[TLMEnvironment updatePathEnvironment][43733]	Using PATH = "(
    "/Library/TeX/texbin",
    "/usr/local/bin",
    "/usr/bin",
    "/bin",
    "/usr/sbin",
    "/sbin"
)"
2023-11-18 20:57:41 +0000 Notice +[TLMEnvironment _checkSystemPythonMajorVersion:minorVersion:][43733]	Using python at '/Applications/TeX/TeX Live Utility.app/Contents/Frameworks/Python.framework/Versions/3.9/bin/python3'
2023-11-18 20:57:41 +0000 Notice +[TLMEnvironment _checkSystemPythonMajorVersion:minorVersion:][43733]	Python version is 3.9.10 (v3.9.10:f2f3f53782, Jan 13 2022, 16:55:46) 
[Clang 13.0.0 (clang-1300.0.29.30)]
2023-11-18 20:57:41 +0000 Notice +[TLMEnvironment updateEnvironment][43733]	Nothing to update for /usr/local/texlive/2023
2023-11-18 20:57:41 +0000 Notice -[TLMDatabase _downloadDatabaseHead][43733]	Checking the repository version.  Please be patient.
2023-11-18 20:57:41 +0000 Notice -[TLMDatabase _downloadDatabaseHead][43733]	Downloading at least 2048 bytes of tlpdb for a version check…
2023-11-18 20:57:41 +0000 Notice -[TLMDatabase _downloadDatabaseHead][43733]	Downloaded 196608 bytes of tlpdb for version check
2023-11-18 20:57:41 +0000 Notice -[TLMEnvironment initWithInstallDirectory:][43733]	Looks like you're using TeX Live 2023
2023-11-18 20:57:41 +0000 Notice -[TLMEnvironment _checkForRootPrivileges][43733]	Root permission required for installation at /usr/local/texlive/2023
2023-11-18 20:57:41 +0000 Notice +[TLMEnvironment _logEnvironment][43733]	Current environment from /usr/bin/env:
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
__CFBundleIdentifier=com.googlecode.mactlmgr.tlu
CC_FOR_BUILD=no_compiler_found
COMMAND_MODE=unix2003
DISPLAY=/private/tmp/com.apple.launchd.lksNSAE1iB/org.xquartz:0
HOME=/Users/Devin
LOGNAME=Devin
PATH=/Library/TeX/texbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
SHELL=/bin/zsh
SQLITE_EXEMPT_PATH_FROM_VNODE_GUARDS=/Users/Devin/Library/WebKit/Databases
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.MPS6skV9nK/Listeners
TMPDIR=/var/folders/y0/zvly4kr52k73ww89tjtm4_yw0000gn/T/
USER=Devin
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
2023-11-18 20:57:41 +0000 Notice -[TLMLogWindowController awakeFromNib][43733]	Loaded log window controller
2023-11-18 20:57:41 +0000 Notice -[TLMDatabase _reloadFromLocalFile][43733]	Reloading local tlpdb from file:///usr/local/texlive/2023/tlpkg/texlive.tlpdb
2023-11-18 20:57:45 +0000 Notice -[TLMDatabase _reloadFromLocalFile][43733]	Took 3.48 seconds to reload local tlpdb
2023-11-18 20:57:45 +0000 Notice -[TLMDatabase _downloadDatabaseHead][43733]	Checking the repository version.  Please be patient.
2023-11-18 20:57:45 +0000 Notice -[TLMDatabase _downloadDatabaseHead][43733]	Downloading at least 2048 bytes of tlpdb for a version check…
2023-11-18 20:57:45 +0000 Notice -[TLMDatabase connection:willSendRequest:redirectResponse:][43733]	redirected request to https://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet/tlpkg/texlive.tlpdb
2023-11-18 20:57:45 +0000 Notice -[TLMDatabase _downloadDatabaseHead][43733]	Downloaded 7923 bytes of tlpdb for version check
2023-11-18 20:57:46 +0000 Notice -[TLMEnvironment _getValidServerURL:repositoryYear:fromURL:][43733]	Repository version appears to be 2023; a young TeX Live
2023-11-18 20:57:46 +0000 Notice -[TLMFaviconCache downloadIconForURL:delegate:][43733]	Will look for favicon at https://ctan.math.washington.edu/favicon.ico
2023-11-18 20:57:46 +0000 Notice +[TLMLaunchAgentController pathOfUpdatedAgentForVenturaStupidity][43733]	Checking to see if we need to rewrite the launch agent plist because Ventura sucks.
2023-11-18 20:57:46 +0000 Notice -[TLMMainWindowController _refreshUpdatedPackageListFromLocation:][43733]	Refreshing list of updated packages…
2023-11-18 20:57:46 +0000 Notice -[TLMFaviconCache connectionDidFinishLoading:][43733]	Finished downloading favicon of length 287
2023-11-18 20:57:49 +0000 Notice -[TLMMainWindowController _paperSizeCheckTerminated:][43733]	System paper size = letter, pdftex paper size = letter
2023-11-18 20:57:49 +0000 Notice -[TLMOperation main][43733]	Successfully executed `/Library/TeX/texbin/tlmgr --machine-readable --repository https://www.preining.info/tlgpg/ update --list --all`
2023-11-18 20:57:49 +0000 Notice -[TLMOperation main][43733]	start load https://www.preining.info/tlgpg/
finish load https://www.preining.info/tlgpg/
2023-11-18 20:57:49 +0000 Notice -[TLMMainWindowController _handleListGPGUpdatesFinishedNotification:][43733]	Found 0 tlgpg packages to update from https://www.preining.info/tlgpg/
2023-11-18 20:57:51 +0000 Notice -[TLMOperation main][43733]	Successfully executed `/Library/TeX/texbin/tlmgr --machine-readable --repository https://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet/ update --list --all`
2023-11-18 20:57:51 +0000 Notice -[TLMOperation main][43733]	start load https://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet/
finish load https://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet/
2023-11-18 20:57:53 +0000 Notice -[TLMMainWindowController _handleListUpdatesFinishedNotification:][43733]	Critical updates detected: (
    "texlive.infra"
)
2023-11-18 20:59:50 +0000 Notice -[TLMMainWindowController _isCorrectDatabaseVersionAtURL:][43733]	Checking database version in case preferences have been changed…
2023-11-18 20:59:50 +0000 Notice -[TLMMainWindowController _updateAllPackagesFromRepository:][43733]	Beginning infrastructure update from https://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet/
2023-11-18 20:59:50 +0000 Notice -[TLMInfraUpdateOperation _synchronouslyDownloadURL:toPath:][43733]	Downloading URL: https://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet/update-tlmgr-latest.sh
2023-11-18 20:59:50 +0000 Notice -[TLMInfraUpdateOperation download:willSendRequest:redirectResponse:][43733]	Download redirected to https://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet/update-tlmgr-latest.sh, expecting 0 bytes.
2023-11-18 20:59:51 +0000 Notice -[TLMInfraUpdateOperation download:didReceiveResponse:][43733]	Will download 9450968 bytes…
2023-11-18 20:59:51 +0000 Notice -[TLMInfraUpdateOperation download:didReceiveDataOfLength:][43733]	Received 21% of 9450968 bytes…
2023-11-18 20:59:51 +0000 Notice -[TLMInfraUpdateOperation download:didReceiveDataOfLength:][43733]	Received 41% of 9450968 bytes…
2023-11-18 20:59:52 +0000 Notice -[TLMInfraUpdateOperation download:didReceiveDataOfLength:][43733]	Received 61% of 9450968 bytes…
2023-11-18 20:59:52 +0000 Notice -[TLMInfraUpdateOperation download:didReceiveDataOfLength:][43733]	Received 82% of 9450968 bytes…
2023-11-18 20:59:52 +0000 Notice -[TLMInfraUpdateOperation downloadDidFinish:][43733]	Download of 9450968 bytes complete
2023-11-18 20:59:52 +0000 Notice -[TLMInfraUpdateOperation _downloadUpdateScript][43733]	First line of downloaded file is: "#!/bin/sh"…good!
2023-11-18 20:59:52 +0000 Notice -[TLMInfraUpdateOperation _synchronouslyDownloadURL:toPath:][43733]	Downloading URL: https://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet/update-tlmgr-latest.sh.sha512
2023-11-18 20:59:52 +0000 Notice -[TLMInfraUpdateOperation download:willSendRequest:redirectResponse:][43733]	Download redirected to https://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet/update-tlmgr-latest.sh.sha512, expecting 0 bytes.
2023-11-18 20:59:52 +0000 Notice -[TLMInfraUpdateOperation download:didReceiveResponse:][43733]	Will download 153 bytes…
2023-11-18 20:59:52 +0000 Notice -[TLMInfraUpdateOperation download:didReceiveDataOfLength:][43733]	Received 100% of 153 bytes…
2023-11-18 20:59:52 +0000 Notice -[TLMInfraUpdateOperation downloadDidFinish:][43733]	Download of 153 bytes complete
2023-11-18 20:59:52 +0000 Notice -[TLMInfraUpdateOperation _compare512][43733]	SHA512 signature looks okay
2023-11-18 20:59:52 +0000 Notice -[TLMAuthorizedOperation main][43733]	Checking code signature before running tlu_ipctask as root…
2023-11-18 20:59:52 +0000 Notice /usr/bin/codesign[43733]	/Applications/TeX/TeX Live Utility.app/Contents/MacOS/tlu_ipctask: valid on disk
/Applications/TeX/TeX Live Utility.app/Contents/MacOS/tlu_ipctask: satisfies its Designated Requirement
2023-11-18 20:59:52 +0000 Notice -[TLMAuthorizedOperation main][43733]	Signature was valid, okay to run tlu_ipctask
2023-11-18 20:59:57 +0000 Notice -[TLMAuthorizedOperation main][43733]	Invoking privileged task via AuthorizationExecuteWithPrivileges
2023-11-18 20:59:57 +0000 Notice tlu_ipctask[43987]	dropped privileges to user nobody
2023-11-18 20:59:58 +0000 Notice -[TLMAuthorizedOperation setWrapperPID:][43733]	tlu_ipctask checking in:  tlu_ipctask pid = 43987
2023-11-18 20:59:59 +0000 Notice -[TLMAuthorizedOperation setUnderlyingPID:][43733]	tlu_ipctask checking in: pid = 43988 (/var/folders/y0/zvly4kr52k73ww89tjtm4_yw0000gn/T/TLMInfraUpdateOperation.pI5avI/update-tlmgr-latest.sh --nox11 -- --debug)
2023-11-18 20:59:59 +0000 Notice tlu_ipctask[43987]	tlu_ipctask: child HOME = '/var/root'
2023-11-18 20:59:59 +0000 Notice tlu_ipctask[43987]	tlu_ipctask: current HOME = '/var/empty'
2023-11-18 20:59:59 +0000 Notice tlu_ipctask[43987]	Verifying archive integrity... All good.
2023-11-18 20:59:59 +0000 Warning tlu_ipctask[43987]	0%    44%    88%  100%  /var/folders/y0/zvly4kr52k73ww89tjtm4_yw0000gn/T/TLMInfraUpdateOperation.pI5avI/update-tlmgr-latest.sh: line 204: /dev/tty: Device not configured
2023-11-18 20:59:59 +0000 Notice tlu_ipctask[43987]	Uncompressing TeX Live Manager Updater
2023-11-18 20:59:59 +0000 Notice tlu_ipctask[43987]	./runme.sh: updating in /usr/local/texlive/2023...
2023-11-18 21:00:00 +0000 Notice tlu_ipctask[43987]	./runme.sh: tlmgr version says this is TeX Live 2023,
2023-11-18 21:00:00 +0000 Notice tlu_ipctask[43987]	./runme.sh: and this updater script created: Thu Nov 16 02:12:22 CET 2023.
2023-11-18 21:00:00 +0000 Notice tlu_ipctask[43987]	./runme.sh: proceeding with tlmgr update.
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ test x = x--upgrade
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ echo './runme.sh: proceeding with tlmgr update.'
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ mv ./master/bin .
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ mkdir ./installer
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ mv ./master/tlpkg/installer/tar.exe ./installer
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ mv ./master/tlpkg/installer/xz ./installer
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ mv ./master/tlpkg/installer/wget ./installer
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ mv ./master/tlpkg/installer/lz4 ./installer
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ cd master
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ tar cf - LICENSE.CTAN LICENSE.TL README README.usergroups index.html readme-html.dir readme-txt.dir release-texlive.txt texmf-dist tlpkg
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ cd /usr/local/texlive/2023
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ tar xf -
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ t_instdir=/usr/local/texlive/2023/tlpkg/installer
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ t_xzdir=/usr/local/texlive/2023/tlpkg/installer/xz
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ t_wgetdir=/usr/local/texlive/2023/tlpkg/installer/wget
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ mkdir -p /usr/local/texlive/2023/tlpkg/installer/xz /usr/local/texlive/2023/tlpkg/installer/wget
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ src_tlpobj=master/tlpkg/tlpobj
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ tlpobjs=master/tlpkg/tlpobj/texlive.infra.tlpobj
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ test -n 1
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	pwd
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	++ pwd
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ : 'here (/var/folders/y0/zvly4kr52k73ww89tjtm4_yw0000gn/T/selfgz439883120):'
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ ls
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	bin
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	installer
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	master
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	runme.sh
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ : installer:
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ ls installer
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	lz4
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	tar.exe
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	wget
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	xz
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ : installer/wget:
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ ls installer/wget
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ : installer/xz:
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ ls installer/xz
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ : ROOT/bin=/usr/local/texlive/2023/bin:
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ ls /usr/local/texlive/2023/bin
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	universal-darwin
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ for a in '"$ROOT"/bin/*'
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ test -d /usr/local/texlive/2023/bin/universal-darwin
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	basename "$a"
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	++ basename /usr/local/texlive/2023/bin/universal-darwin
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ b=universal-darwin
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ test universal-darwin = man
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ echo './runme.sh: updating /usr/local/texlive/2023/bin/universal-darwin ...'
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ tlpobjs='master/tlpkg/tlpobj/texlive.infra.tlpobj master/tlpkg/tlpobj/texlive.infra.universal-darwin.tlpobj'
2023-11-18 21:00:00 +0000 Notice tlu_ipctask[43987]	./runme.sh: updating /usr/local/texlive/2023/bin/universal-darwin ...
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ cd bin
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ tar cf - universal-darwin
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ cd /usr/local/texlive/2023/bin
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ tar xf -
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ test -r installer/xz/xz.universal-darwin
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ test -r installer/xz/xz.universal-darwin.exe
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ echo universal-darwin
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ egrep 'win32|windows'
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	pwd
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	++ pwd
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ echo './runme.sh: no xz.[universal-darwin][.exe] binary for /usr/local/texlive/2023/bin/universal-darwin in /var/folders/y0/zvly4kr52k73ww89tjtm4_yw0000gn/T/selfgz439883120/installer/xz.'
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	./runme.sh: no xz.[universal-darwin][.exe] binary for /usr/local/texlive/2023/bin/universal-darwin in /var/folders/y0/zvly4kr52k73ww89tjtm4_yw0000gn/T/selfgz439883120/installer/xz.
2023-11-18 21:00:00 +0000 Warning tlu_ipctask[43987]	+ exit 1
2023-11-18 21:00:00 +0000 Notice -[TLMAuthorizedOperation _runUntilChildExit][43733]	kqueue noted that pid 43988 exited (/var/folders/y0/zvly4kr52k73ww89tjtm4_yw0000gn/T/TLMInfraUpdateOperation.pI5avI/update-tlmgr-latest.sh --nox11 -- --debug)
2023-11-18 21:00:00 +0000 Notice tlu_ipctask[43987]	child process pid = 43988 exited
2023-11-18 21:00:01 +0000 Notice tlu_ipctask[43987]	exit status of pid = 43988 was 1
2023-11-18 21:00:01 +0000 Notice -[TLMAuthorizedOperation _runUntilChildExit][43733]	exit status of pid = 43987 was 1
2023-11-18 21:00:01 +0000 Notice -[TLMAuthorizedOperation _runUntilChildExit][43733]	kqueue noted that tlu_ipctask (pid = 43987) exited with status 1
2023-11-18 21:00:01 +0000 Notice -[TLMInfraUpdateOperation main][43733]	Removed temp directory "/var/folders/y0/zvly4kr52k73ww89tjtm4_yw0000gn/T/TLMInfraUpdateOperation.pI5avI"
```

**Comment by amaxwell** [comment] 2023-11-18 22:15
The TeX Live team is investigating the issue and will hopefully have a fix soon. If there's something you need immediately, you can update via `tlmgr` on the command line.

**Comment by fjhickernell** [comment] 2023-11-19 23:38
Same error for me on M2 Mac with Sonoma 14.1.1

**Comment by devincaughey** [comment] 2023-11-19 23:58
FYI, updating from the command line worked for me.

**Comment by subidit** [comment] 2023-11-20 14:30
I had the same problem. 
Fixed it with the following command in terminal -

`sudo tlmgr update --self`

Now it's updating all packages as intended. Cheers.

**Comment by amaxwell** [comment] 2023-11-20 15:26
If you are bitten by this problem, you can now work around it in TeX Live Utility by holding down the option key and choosing "Install TeX Live Manager From Critical Repository" from the "Actions" menu.

**Comment by fjhickernell** [comment] 2023-11-22 00:05
> I had the same problem. Fixed it with the following command in terminal -
> 
> `sudo tlmgr update --self`
> 
> Now it's updating all packages as intended. Cheers.

This was the instructions that I needed.  Thanks a lot.

**Comment by amaxwell** [comment] 2023-11-23 01:23
Fixed in upstream TeX Live

**Closed by amaxwell** 2023-11-23 01:23 UTC
