### ISSUE TITLE
GPG Install fails (2019 older than 2100)

### ISSUE THREAD

**Issue by skupfer** [amaxwell/tlutility#83] opened 2020-03-15 21:39 UTC
Hello

did a fresh install of MacTex 2019 on my laptop. Cannot enable secure check due to this installation error

```
2020-03-15 18:14:37 +0000 Notice +[TLMEnvironment initialize][10165]	Welcome to TeX Live Utility 1.36, running under Mac OS X Version 10.15.3 (Build 19D76) with 8/8 processors active and 16.0 GB physical memory.
2020-03-15 18:14:37 +0000 Notice +[TLMEnvironment _checkProcessUmask][10165]	Process umask = 022
2020-03-15 18:14:37 +0000 Notice __TLMProxySettingsChanged[10165]	Trying to find a proxy for http://mirror.ctan.org/systems/texlive/tlnet using PAC http://wpad/wpad.dat…
2020-03-15 18:14:37 +0000 Notice __TLMPacCallback[10165]	Proxy list = (null)
2020-03-15 18:14:37 +0000 Notice __TLMPacCallback[10165]	Error finding proxy: Error Domain=NSURLErrorDomain Code=-1003 "(null)"
2020-03-15 18:14:37 +0000 Notice +[TLMEnvironment updateEnvironment][10165]	Setting up a new environment for /usr/local/texlive/2019…
2020-03-15 18:14:37 +0000 Notice +[TLMEnvironment updatePathEnvironment][10165]	Using PATH = "(
    "/Library/TeX/texbin",
    "/usr/bin",
    "/bin",
    "/usr/sbin",
    "/sbin"
)"
2020-03-15 18:14:37 +0000 Notice +[TLMEnvironment _checkSystemPythonMajorVersion:minorVersion:][10165]	Using python at '/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python'
2020-03-15 18:14:37 +0000 Notice +[TLMEnvironment _checkSystemPythonMajorVersion:minorVersion:][10165]	Python version is 2.7.16 (default, Dec 13 2019, 18:00:32) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.32.4) (-macos10.15-objc-s
2020-03-15 18:14:37 +0000 Notice +[TLMEnvironment updateEnvironment][10165]	Nothing to update for /usr/local/texlive/2019
2020-03-15 18:14:37 +0000 Notice -[TLMDatabase _downloadDatabaseHead][10165]	Checking the repository version.  Please be patient.
2020-03-15 18:14:37 +0000 Notice -[TLMDatabase _downloadDatabaseHead][10165]	Downloading at least 2048 bytes of tlpdb for a version check…
2020-03-15 18:14:37 +0000 Notice -[TLMDatabase _downloadDatabaseHead][10165]	Downloaded 196608 bytes of tlpdb for version check
2020-03-15 18:14:38 +0000 Notice -[TLMEnvironment initWithInstallDirectory:][10165]	Looks like you're using TeX Live 2019
2020-03-15 18:14:38 +0000 Notice -[TLMEnvironment _checkForRootPrivileges][10165]	Root permission required for installation at /usr/local/texlive/2019
2020-03-15 18:14:38 +0000 Notice +[TLMEnvironment _logEnvironment][10165]	Current environment from /usr/bin/env:
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
CC_FOR_BUILD=no_compiler_found
HOME=/Users/kupfer
LOGNAME=kupfer
PATH=/Library/TeX/texbin:/usr/bin:/bin:/usr/sbin:/sbin
SHELL=/bin/zsh
SQLITE_EXEMPT_PATH_FROM_VNODE_GUARDS=/Users/kupfer/Library/WebKit/Databases
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.nxGUUnT1FF/Listeners
TMPDIR=/var/folders/5l/3v6506ks3mdd6rclv28brrq00000gn/T/
USER=kupfer
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
2020-03-15 18:14:38 +0000 Notice -[TLMLogWindowController awakeFromNib][10165]	Loaded log window controller
2020-03-15 18:14:38 +0000 Notice -[TLMDatabase _reloadFromLocalFile][10165]	Reloading local tlpdb from file:///usr/local/texlive/2019/tlpkg/texlive.tlpdb
2020-03-15 18:14:49 +0000 Notice -[TLMDatabase _reloadFromLocalFile][10165]	Took 10.94 seconds to reload local tlpdb
2020-03-15 18:14:53 +0000 Notice -[TLMAuthorizedOperation main][10165]	Checking code signature before running tlu_ipctask as root…
2020-03-15 18:14:53 +0000 Notice /usr/bin/codesign[10165]	/Applications/TeX/TeX Live Utility.app/Contents/MacOS/tlu_ipctask: valid on disk
/Applications/TeX/TeX Live Utility.app/Contents/MacOS/tlu_ipctask: satisfies its Designated Requirement
2020-03-15 18:14:53 +0000 Notice -[TLMAuthorizedOperation main][10165]	Signature was valid, okay to run tlu_ipctask
2020-03-15 18:14:58 +0000 Notice -[TLMAuthorizedOperation main][10165]	Invoking privileged task via AuthorizationExecuteWithPrivileges
2020-03-15 18:14:58 +0000 Notice tlu_ipctask[10226]	dropped privileges to user nobody
2020-03-15 18:14:58 +0000 Notice -[TLMMainWindowController _paperSizeCheckTerminated:][10165]	System paper size = a4, pdftex paper size = a4
2020-03-15 18:14:59 +0000 Notice -[TLMAuthorizedOperation setWrapperPID:][10165]	tlu_ipctask checking in:  tlu_ipctask pid = 10226
2020-03-15 18:15:00 +0000 Notice -[TLMAuthorizedOperation setUnderlyingPID:][10165]	tlu_ipctask checking in: pid = 10227 (/Library/TeX/texbin/tlmgr --machine-readable --repository http://www.preining.info/tlgpg/ --persistent-downloads install --reinstall tlgpg)
2020-03-15 18:15:00 +0000 Notice tlu_ipctask[10226]	tlu_ipctask: child HOME = '/var/root'
2020-03-15 18:15:00 +0000 Notice tlu_ipctask[10226]	tlu_ipctask: current HOME = '/var/empty'
2020-03-15 18:15:05 +0000 Warning tlu_ipctask[10226]	start load http://www.preining.info/tlgpg/
2020-03-15 18:15:06 +0000 Warning tlu_ipctask[10226]	fail load http://www.preining.info/tlgpg/
2020-03-15 18:15:06 +0000 Warning tlu_ipctask[10226]	
2020-03-15 18:15:06 +0000 Warning tlu_ipctask[10226]	tlmgr: Local TeX Live (2019) is older than remote repository (2100).
2020-03-15 18:15:06 +0000 Warning tlu_ipctask[10226]	Cross release updates are only supported with
2020-03-15 18:15:06 +0000 Warning tlu_ipctask[10226]	update-tlmgr-latest(.sh/.exe) --update
2020-03-15 18:15:06 +0000 Warning tlu_ipctask[10226]	See https://tug.org/texlive/upgrade.html for details.
2020-03-15 18:15:06 +0000 Notice -[TLMAuthorizedOperation _runUntilChildExit][10165]	kqueue noted that pid 10227 exited (/Library/TeX/texbin/tlmgr --machine-readable --repository http://www.preining.info/tlgpg/ --persistent-downloads install --reinstall tlgpg)
2020-03-15 18:15:06 +0000 Notice tlu_ipctask[10226]	child process pid = 10227 exited
2020-03-15 18:15:07 +0000 Error tlu_ipctask[10226]	Value of errno is Operation not permitted
2020-03-15 18:15:07 +0000 Error tlu_ipctask[10226]	*** ERROR *** exit status of pid = 10227 was 1
2020-03-15 18:15:07 +0000 Notice -[TLMAuthorizedOperation _runUntilChildExit][10165]	waitpid returned 10226, WIFEXITED(256) = 1, errno = 2 (No error)
2020-03-15 18:15:07 +0000 Notice -[TLMAuthorizedOperation _runUntilChildExit][10165]	kqueue noted that tlu_ipctask (pid = 10226) exited with status 1
2020-03-15 18:15:08 +0000 Notice -[TLMDatabase _downloadDatabaseHead][10165]	Checking the repository version.  Please be patient.
2020-03-15 18:15:08 +0000 Notice -[TLMDatabase _downloadDatabaseHead][10165]	Downloading at least 2048 bytes of tlpdb for a version check…
2020-03-15 18:15:08 +0000 Notice -[TLMDatabase connection:willSendRequest:redirectResponse:][10165]	redirected request to http://ctan.mirror.norbert-ruehl.de/systems/texlive/tlnet/tlpkg/texlive.tlpdb
2020-03-15 18:15:08 +0000 Notice -[TLMDatabase _downloadDatabaseHead][10165]	Downloaded 5525 bytes of tlpdb for version check
2020-03-15 18:15:08 +0000 Notice -[TLMEnvironment _getValidServerURL:repositoryYear:fromURL:][10165]	Repository version appears to be 2019; a mature TeX Live
2020-03-15 18:15:08 +0000 Notice -[TLMMainWindowController _refreshUpdatedPackageListFromLocation:][10165]	Refreshing list of updated packages…
2020-03-15 18:15:22 +0000 Notice -[TLMOperation main][10165]	Successfully executed `/Library/TeX/texbin/tlmgr --machine-readable --repository http://ctan.mirror.norbert-ruehl.de/systems/texlive/tlnet/ update --list --all`
2020-03-15 18:15:22 +0000 Notice -[TLMOperation main][10165]	start load http://ctan.mirror.norbert-ruehl.de/systems/texlive/tlnet/
TeX Live 2019 is frozen forever and will no
longer be updated.  This happens in preparation for a new release.

If you're interested in helping to pretest the new release (when
pretests are available), please read https://tug.org/texlive/pretest.html.
Otherwise, just wait, and the new release will be ready in due time.
finish load http://ctan.mirror.norbert-ruehl.de/systems/texlive/tlnet/
2020-03-15 18:33:11 +0000 Notice __TLMProxySettingsChanged[10165]	Trying to find a proxy for http://mirror.ctan.org/systems/texlive/tlnet using PAC http://wpad/wpad.dat…
2020-03-15 18:33:14 +0000 Notice __TLMPacCallback[10165]	Proxy list = (null)
2020-03-15 18:33:14 +0000 Notice __TLMPacCallback[10165]	Error finding proxy: Error Domain=NSURLErrorDomain Code=-1003 "(null)"
```

**Comment by amaxwell** [comment] 2020-03-16 15:11
I'll have to ask the TeX Live maintainers about this. I'm not sure if there's anything I can do.

**Comment by norbusan** [comment] 2020-03-17 01:09
The problem is as follows:
- the tlgpg repo is for all releases, that is for now for 2020 (or in fact for 2100, we switch it always during tlpretest, and I thought we could extended it directly to 2100 ;-)
- tlutility uses `tlmgr --repo .....` to install
- tlmgr in 2019 bails out when the main repository in use has higher release year (2020/2100 in this case) than the release year of tlmgr itself (2019).
- using `tlmgr --repo ....` makes `....` the main repo for this invocation

This has already been fixed in tlmgr in 2020 tlpretest by making tlmgr check whether the release year contains an additional tag. The repos I maintain have all format `YYYY-somename`, and if this `-somename` part is present, tlmgr (2020) will not bail out even when used with `--repo ...`.

There is another solution, namely tlmgr even in 2019 does not do this release year check for sub-repositories, that is, when you use multiple repository setup instead of `--repo`. But note that tlutility does not support this by now, AFAIR.

Temporary solution for those who want to install tlgpg on a new MacTeX 2019 installation (needs to be done in the command line, maybe with sudo, I don't know how MacTeX is set up):
```
tlmgr repository add http://www.preining.info/tlgpg/ tlgpg
tlmgr pinning add tlgpg '*'
tlmgr install tlgpg
tlmgr pinning remove tlgpg '*'
tlmgr repository remove tlgpg
```
That should fix it.

**Closed** 2021-03-02 04:45 UTC
