### ISSUE TITLE
gpg verification in TeX Live Utility does not work

### ISSUE THREAD

**Issue by rodyager** [amaxwell/tlutility#41] opened 2016-04-21 08:45 UTC
I have gpg2 installed in /usr/local/bin  --- which is the standard location for the MacOS GnuPG modern installer.  ( https://sourceforge.net/p/gpgosx/docu/Home/ )  [Well, actually /usr/local/bin/gpg2 is a sym link to /usr/local/gnupg-2.1/bin/gpg2 ]

As a result, gpg verification works for the command line tool. However, it does not work when using the TLU GUI.

The cause of this is the explicit removal of /usr/local/bin from the PATH environment variable in  the updatePathEnvironment method within  TLMEnvironment.m

[It's unclear how the code here could possibly have been responsible the problem mentioned in the 17 Nov 2014 comment]

Rod

**Comment by amaxwell** [comment] 2016-04-21 14:43
Thanks, the gpg problem is known, and I plan to add an explicit path for gpg via one of tlmgr's environment variables. I just haven't gotten to it yet, since fixing the sha512 problem was a higher priority.

The 17 Nov 2014 comment is accurate; I bundle several python tools in TLU, and that path issue was the cause of _multiple_ mysterious python problems over the years.

**Comment by amaxwell** [comment] 2016-05-07 17:44
I've added a different fix for this, which installs a gpg binary in the TL tree after prompting the user; at some point, I may add support for the environment variable.

**Closed by amaxwell** 2016-05-07 17:44 UTC
